global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['fastapi_app:8000']

  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['jenkins_master:8080']
